CREATE TABLE Users (
  id BIGINT IDENTITY(1,1) PRIMARY KEY,
  email NVARCHAR(190) NOT NULL UNIQUE,
  password_hash NVARCHAR(255) NOT NULL,
  display_name NVARCHAR(190) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
